title: Makoto's Blog
description: > # this means to ignore newlines until "baseurl:"
  Blog with theme Future Imperfect<br>
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://future-imperfect.kaptn.ru" # the base hostname & protocol for your site, e.g. http://example.com


author:
  name: 'Makoto'
  last_name: 'Imada'
  cv: ''
  avatar: '/images/avatar.jpeg'
  github_username:  mkt1733
  email: todo@todo.com
  vk_id: what_is_this
  telegram_name: telegram_none
  logo: '/images/logo.svg'

# Build settings
markdown: kramdown

permalink: /:categories/:year/:title.html


